#!/bin/sh
# gen_dns_protocols.sh — regenerate dns_protocols.inc from the nDPI source.
#
# dnsteerd can only populate a set for a protocol that nDPI classifies from
# a DNS name (host/domain patterns). Binary/flow-detected protocols (RTP,
# STUN, the *_Call family, …) are never reachable from DNS and would yield
# permanently empty sets. This script lists the protocol display-names that
# carry DNS/host (domain) patterns, by scanning nDPI's host-match tables.
#
# The display-name is the 2nd field of each host entry
# ( { "domain", "ProtoName", NDPI_PROTOCOL_X, ... } ); IP entries
# ( { 0xHEX, prefixlen, NDPI_PROTOCOL_X } ) have no quoted name and are
# skipped — IP matching is not DNS-routable.
#
# Run it against the SAME nDPI version dnsteerd links against. Default source
# is the installed headers dir (/usr/include/ndpi) when its host-match tables
# are packaged there — that guarantees a match with the linked lib:
#   ./gen_dns_protocols.sh [<dir>] [version] > dns_protocols.inc
# (<dir> holds ndpi_content_match.c.inc + inc_generated/. Release tarballs ship
#  ndpi_config.h.in unconfigured, so pass the version as 2nd arg in that case.)
set -eu

SRC="${1:-/usr/include/ndpi}"
ver="${2:-}"
if [ -z "$ver" ]; then
  for cfg in "$SRC/ndpi_config.h" "$SRC/../include/ndpi_config.h"; do
    [ -f "$cfg" ] || continue
    ver=$(sed -nE 's/.*NDPI_GIT_RELEASE[[:space:]]+"([^"]+)".*/\1/p' "$cfg" | head -1)
    [ -n "$ver" ] && break
  done
fi

names=$(awk -F'"' '
    /NDPI_PROTOCOL_/ && NF >= 5 && $1 ~ /^[[:space:]]*\{[[:space:]]*$/ { print $4 }
  ' "$SRC/ndpi_content_match.c.inc" "$SRC"/inc_generated/*.c.inc 2>/dev/null \
  | sort -u | sed '/^$/d')

# Échec bruyant plutôt qu'une liste vide : si les tables host ne sont pas là
# (nDPI .inc absents de $SRC), dnsteerd ne routerait plus rien silencieusement.
if [ -z "$names" ]; then
  echo "gen_dns_protocols.sh: aucune table host trouvée sous '$SRC'" >&2
  echo "  (ndpi_content_match.c.inc + inc_generated/ absents — cf. README)" >&2
  exit 1
fi

printf '/* Generated by gen_dns_protocols.sh from nDPI %s — DO NOT EDIT.\n' "${ver:-unknown}"
printf ' *\n'
printf ' * Protocol display-names with DNS/host (domain) patterns: the only ones\n'
printf ' * dnsteerd can populate (classified from a DNS name). Regenerate on an\n'
printf ' * nDPI bump:  ./gen_dns_protocols.sh <nDPI/src/lib> > dns_protocols.inc\n'
printf ' */\n'
printf 'static const char *const dnsteerd_host_protos[] = {\n'
printf '%s\n' "$names" | sed -E 's/.*/\t"&",/'
printf '};\n'
